import type { VectorizePreset } from "./types";

export const PRESETS: VectorizePreset[] = [
  {
    id: "logo",
    label: "Logo",
    description: "カラーロゴ標準。背景除去強め、滑らかさ中。",
    mode: "color",
    backgroundMode: "remove-white",
    colorPrecision: 6,
    whiteThreshold: 32,
    edgeSoftness: 16,
    removeFringe: true,
    filterSpeckle: 8,
    cornerThreshold: 60,
    segmentLength: 4.0,
    spliceThreshold: 45,
  },
  {
    id: "icon",
    label: "Icon",
    description: "アイコン向け。色数を抑え、形をくっきり残す。",
    mode: "color",
    backgroundMode: "remove-white",
    colorPrecision: 8,
    whiteThreshold: 28,
    edgeSoftness: 12,
    removeFringe: true,
    filterSpeckle: 6,
    cornerThreshold: 50,
    segmentLength: 3.5,
    spliceThreshold: 45,
  },
  {
    id: "simple-color",
    label: "Simple Color",
    description: "色数を多めに残す。装飾的なイラスト向け。",
    mode: "color",
    backgroundMode: "auto",
    colorPrecision: 7,
    whiteThreshold: 24,
    edgeSoftness: 12,
    removeFringe: true,
    filterSpeckle: 4,
    cornerThreshold: 60,
    segmentLength: 4.0,
    spliceThreshold: 45,
  },
  {
    id: "monochrome",
    label: "Monochrome",
    description: "2 値化。単色シルエット logo 用。",
    mode: "bw",
    backgroundMode: "remove-white",
    colorPrecision: 1,
    whiteThreshold: 36,
    edgeSoftness: 18,
    removeFringe: true,
    filterSpeckle: 10,
    cornerThreshold: 70,
    segmentLength: 5.0,
    spliceThreshold: 60,
  },
];

export const findPreset = (id: string): VectorizePreset | undefined =>
  PRESETS.find((p) => p.id === id);
